# Generated by Django 6.0.3 on 2026-03-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_replace_quizprogress_with_courseprogress'),
        ('user_progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgressRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.courseprogress',),
        ),
        migrations.CreateModel(
            name='ModuleProgressRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Module Progress',
                'verbose_name_plural': 'Module Progress',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.moduleprogress',),
        ),
    ]
