# Generated by Django 6.0.3 on 2026-03-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0004_badge_approval_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='is_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
